Parameters:
  KeyName:
    Description: Name of the existing keypair to ssh into ec2 instance.
    Type: AWS::EC2::KeyPair::KeyName

  VpcId:
    Description: Terraform VPC
    Type: AWS::EC2::VPC::Id

  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Enter Public subnet id

Resources:
  HelloBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead


