Parameters:
  KeyName:
    Description: Name of the existing keypair to ssh into ec2 instance.
    Type: AWS::EC2::KeyPair::KeyName

  VpcId:
    Description: Terraform VPC
    Type: AWS::EC2::VPC::Id
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Enter Public subnet id

Resources:
  HelloBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      SecurityGroupIds:
        - Fn::GetAtt: [InstanceSecurityGroup,GroupId ]
      KeyName: !Ref KeyName
      ImageId: 'ami-0ed9277fb7eb570c9'
      SubnetId: !Ref PublicSubnetId
      InstanceType: 't2.micro'

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      VpcId: !Ref VpcId

outputs:
  EC2InstanceID:
    Description: EC2 instance ID
    Vaule: !Ref Ec2Instance

